ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: 'ci(pre-commit): pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/asottile/pyupgrade
  rev: v3.16.0
  hooks:
  - id: pyupgrade
    args: ["--py38-plus"]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.10
  hooks:
  - id: ruff
    args: ["--fix", "--show-fixes"]
    types_or: [ python, pyi, jupyter ]
  - id: ruff-format
    types_or: [ python, pyi, jupyter ]

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    args: ["--skip=*.ipynb","-L hist,Hist,nd,SubJet,subjet,Subjet,PTD,ptd,fPt,fpt,Ser,ser,hda"]

- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.18
  hooks:
    - id: validate-pyproject
